<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://www.eclipse.org/egf/1.0.0/FactoryComponent" nsPrefix="egf.factorycomponent">
  <eClassifiers xsi:type="ecore:EClass" name="NamedModelElementWithId" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="overall"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="javaIdentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FactoryComponent" eSuperTypes="#//NamedModelElementWithId">
    <eStructuralFeatures xsi:type="ecore:EReference" name="domain" eType="#//Domain"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" lowerBound="1"
        eType="#//Specification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="factory" lowerBound="1"
        eType="#//Factory" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductionPlan" eSuperTypes="#//AbstractFactoryComponentFactory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="factoryComponentInvocations"
        upperBound="-1" eType="#//FactoryComponentInvocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factoryComponentInvocationIds"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FactoryComponentInvocation" eSuperTypes="#//AbstractFactoryComponentFactory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taskFactoryId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factoryComponentId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskFactory" eType="#//TaskFactoryHolder"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domain" eSuperTypes="#//NamedModelElementWithId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specification" eSuperTypes="#//NamedModelElementWithId">
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewpoints" upperBound="-1"
        eType="#//AbstractViewpoint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewpointIds" transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains a map of couple &lt;viewpoint type, List of viewpoint ids for type uased as key>."/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="#//ViewpointType"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eTypeArguments>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractViewpoint" abstract="true" eSuperTypes="#//NamedModelElementWithId"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ViewpointType">
    <eLiterals name="CONTRACT"/>
    <eLiterals name="PATTERN" value="1"/>
    <eLiterals name="MAPPING" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contract" eSuperTypes="#//AbstractViewpoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contractElements" upperBound="-1"
        eType="#//ContractElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContractElement" eSuperTypes="#//NamedModelElementWithId">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contractElementReferences"
        upperBound="-1" eType="#//ContractElementReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factoryComponentId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contractReferenceIds" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contractType" lowerBound="1"
        eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatory" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContractElementReference" eSuperTypes="#//NamedModelElementWithId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referencedContractElementId"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referencedContractElementName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="@deprecated&#xD;&#xA;Use referencedContractElementId instead of."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referencedFactoryComponentId"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedContractElement"
        eType="#//ContractElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//NamedModelElementWithId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeHolderClassName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeHolder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternViewpoint" eSuperTypes="#//AbstractViewpoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="libraries" upperBound="-1"
        eType="#//PatternLibrary" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractPatternElement" abstract="true"
      eSuperTypes="#//NamedModelElementWithId"/>
  <eClassifiers xsi:type="ecore:EClass" name="PatternLibrary" eSuperTypes="#//AbstractPatternElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patternElements" upperBound="-1"
        eType="#//AbstractPatternElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="productionOrchestration"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runtimeOrchestration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternModel" eSuperTypes="#//AbstractPatternElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Factory" eSuperTypes="#//NamedModelElementWithId">
    <eStructuralFeatures xsi:type="ecore:EReference" name="productionPlan" lowerBound="1"
        eType="#//ProductionPlan" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="productionPlanId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFactoryComponentFactory" abstract="true"
      eSuperTypes="#//NamedModelElementWithId">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//Context"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contextId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context" eSuperTypes="#//NamedModelElementWithId">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextElements" lowerBound="1"
        upperBound="-1" eType="#//ContextElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextElement" eSuperTypes="#//NamedModelElementWithId">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contractElementReference"
        eType="#//ContractElementReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readableValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If value is a stringValue then readableValue is equals to value.&lt;br>&#xD;&#xA;Else if  value is a classValue then readableValue is equals to the fully class name according to value attribute content. &#xD;&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contractReferenceId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextType" eType="#//Type"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pluginId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskFactoryHolder" eSuperTypes="#//NamedModelElementWithId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factoryClass" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingViewpoint" eSuperTypes="#//AbstractViewpoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//MappingModel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MappingModel" eSuperTypes="#//NamedModelElementWithId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
