<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pattern"
    nsURI="http://www.eclipse.org/egf/1.0.0/Pattern" nsPrefix="egf.pattern">
  <eClassifiers xsi:type="ecore:EClass" name="Generator" abstract="true" interface="true">
    <eOperations name="generateBody" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return org.eclipse.egf.common.constant.ICommonConstants.EMPTY_STRING;"/>
      </eAnnotations>
      <eParameters name="classLoader_p" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="generateHeader" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="generateFooter" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eOperations name="generatePreMatching" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eOperations name="generatePostMatching" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass #//Generator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="overall"/>
    </eAnnotations>
    <eOperations name="produce" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="StringBuilder stringBuilder = new StringBuilder(generateHeader());&#xD;&#xA;stringBuilder.append(generate(classLoader_p));&#xD;&#xA;stringBuilder.append(generateFooter());&#xD;&#xA;return stringBuilder.toString();"/>
      </eAnnotations>
      <eParameters name="classLoader_p" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="generate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="StringBuilder stringBuilder = new StringBuilder(generatePreMatching());&#xD;&#xA;stringBuilder.append(generateBody(classLoader_p));&#xD;&#xA;stringBuilder.append(generatePostMatching());&#xD;&#xA;return stringBuilder.toString();"/>
      </eAnnotations>
      <eParameters name="classLoader_p" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="addPropertyChangeListener">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="// Avoid the JFace data-binding not very nice error message."/>
      </eAnnotations>
      <eParameters name="propertyName_p" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="listener_p" eType="#//PPropertyChangeListener"/>
    </eOperations>
    <eOperations name="removePropertyChangeListener">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="// Avoid the JFace data-binding not very nice error message."/>
      </eAnnotations>
      <eParameters name="propertyName_p" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="listener_p" eType="#//PPropertyChangeListener"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortId" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logicalName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//relations/ReferenceRelation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//relations/ParameterRelation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callParameters" upperBound="-1"
        eType="#//relations/CallParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="PPropertyChangeListener" instanceClassName="java.beans.PropertyChangeListener"
      serializable="false"/>
  <eSubpackages name="relations" nsURI="egf.pattern.relations" nsPrefix="egf.pattern.relations">
    <eClassifiers xsi:type="ecore:EClass" name="PatternRelation" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterRelation" eSuperTypes="#//relations/PatternRelation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReferenceRelation" eSuperTypes="#//relations/PatternRelation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedPattern" eType="#//Pattern"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CallParameter" eSuperTypes="#//relations/PatternRelation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
