<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="extension"
    nsURI="http://www.eclipse.org/egf/1.0.0/extension" nsPrefix="extension">
  <eClassifiers xsi:type="ecore:EClass" name="ExtendedType" eSuperTypes="platform:/plugin/org.eclipse.egf.model/model/Types.ecore#//Type">
    <eOperations name="getType" lowerBound="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return (Class&lt;T>) org.eclipse.egf.example.type.extension.ExtendedType.class;"/>
      </eAnnotations>
      <eGenericType eClassifier="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaClass">
        <eTypeArguments eTypeParameter="#//ExtendedType/getType/T"/>
      </eGenericType>
      <eTypeParameters name="T">
        <eBounds eClassifier="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
      </eTypeParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.egf.model/model/Types.ecore#//Type"/>
  </eClassifiers>
</ecore:EPackage>
