<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="generationChain"
    nsURI="http://www.eclipse.org/egf/1.0.0/generationChain" nsPrefix="generationChain">
  <eClassifiers xsi:type="ecore:EClass" name="GenerationElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//GenerationChain"
        eOpposite="#//GenerationChain/elements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenerationChain" eSuperTypes="#//GenerationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="factoryComponentName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//GenerationElement" containment="true" eOpposite="#//GenerationElement/container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmfGeneration" eSuperTypes="#//EcoreElement #//PluginProvider">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generateModel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generateEdit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generateEditor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pluginName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePackage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentationGeneration" eSuperTypes="#//EcoreElement #//PluginProvider">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pluginName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputDirectoryPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EcoreElement" abstract="true" eSuperTypes="#//GenerationElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PluginProvider" abstract="true" interface="true">
    <eOperations name="getPluginNames" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
