<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fcore"
    nsURI="http://www.eclipse.org/egf/1.0.0/fcore" nsPrefix="fcore">
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iD" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" abstract="true" eSuperTypes="#//ModelElement">
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eTypeParameters name="T">
        <eBounds eClassifier="#//ActivityContract"/>
      </eTypeParameters>
    </eOperations>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityContract" abstract="true" eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="MandatoryName UniqueName"/>
    </eAnnotations>
    <eOperations name="getActivity" lowerBound="1" eType="#//Activity"/>
    <eOperations name="getActivityContractContainer" lowerBound="1" eType="#//ActivityContractContainer"/>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eTypeParameters name="T">
        <eBounds eClassifier="#//ActivityContract"/>
      </eTypeParameters>
    </eOperations>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatory" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//ContractMode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" containment="true"
        resolveProxies="false">
      <eGenericType eClassifier="#//Type">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityContractContainer" abstract="true"
      eSuperTypes="#//ModelElement">
    <eOperations name="getActivity" eType="#//Activity"/>
    <eOperations name="getActivityContracts" upperBound="-1">
      <eGenericType eTypeParameter="#//ActivityContractContainer/getActivityContracts/T"/>
      <eTypeParameters name="T">
        <eBounds eClassifier="#//ActivityContract"/>
      </eTypeParameters>
    </eOperations>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FactoryComponent" eSuperTypes="#//Activity">
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//FactoryComponentContract"/>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eOperations name="getInvocationContexts" upperBound="-1" eType="#//InvocationContext"/>
    <eOperations name="getInvocationContexts" upperBound="-1" eType="#//InvocationContext">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getInvocationContexts" upperBound="-1" eType="#//InvocationContext">
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eOperations name="getInvocationContexts" upperBound="-1" eType="#//InvocationContext">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityContractContainer"
        eType="#//FactoryComponentContractContainer" containment="true" resolveProxies="false"
        eOpposite="#//FactoryComponentContractContainer/activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewpointContainer" eType="#//ViewpointContainer"
        containment="true" resolveProxies="false" eOpposite="#//ViewpointContainer/factoryComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orchestration" eType="#//Orchestration"
        containment="true" resolveProxies="false" eOpposite="#//Orchestration/factoryComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FactoryComponentContract" eSuperTypes="#//ActivityContract">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="OutModeIsRestricted"/>
    </eAnnotations>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//FactoryComponentContract"/>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocationContexts" lowerBound="1"
        upperBound="-1" eType="#//InvocationContext" resolveProxies="false" eOpposite="#//InvocationContext/factoryComponentExposedContract"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityContractContainer"
        lowerBound="1" eType="#//FactoryComponentContractContainer" eOpposite="#//FactoryComponentContractContainer/activityContracts"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FactoryComponentContractContainer" eSuperTypes="#//ActivityContractContainer">
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eOperations name="getActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
        eType="#//FactoryComponent" eOpposite="#//FactoryComponent/activityContractContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityContracts" lowerBound="1"
        upperBound="-1" eType="#//FactoryComponentContract" containment="true" resolveProxies="false"
        eOpposite="#//FactoryComponentContract/activityContractContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewpointContainer" eSuperTypes="#//ModelElement">
    <eOperations name="getViewpoint" eType="#//Viewpoint">
      <eParameters name="clazz">
        <eGenericType eClassifier="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaClass">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="factoryComponent" lowerBound="1"
        eType="#//FactoryComponent" resolveProxies="false" eOpposite="#//FactoryComponent/viewpointContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewpoints" upperBound="-1"
        eType="#//Viewpoint" containment="true" resolveProxies="false" eOpposite="#//Viewpoint/viewerpointContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Viewpoint" abstract="true" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewerpointContainer" lowerBound="1"
        eType="#//ViewpointContainer" resolveProxies="false" eOpposite="#//ViewpointContainer/viewpoints"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Orchestration" abstract="true" eSuperTypes="#//ModelElement">
    <eOperations name="getInvocationContexts" upperBound="-1" eType="#//InvocationContext"/>
    <eOperations name="getInvocationContexts" upperBound="-1" eType="#//InvocationContext">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getInvocationContexts" upperBound="-1" eType="#//InvocationContext">
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eOperations name="getInvocationContexts" upperBound="-1" eType="#//InvocationContext">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eOperations name="getOrchestrationContexts" upperBound="-1" eType="#//OrchestrationContext"/>
    <eOperations name="getOrchestrationContexts" upperBound="-1" eType="#//OrchestrationContext">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="factoryComponent" lowerBound="1"
        eType="#//FactoryComponent" resolveProxies="false" eOpposite="#//FactoryComponent/orchestration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orchestrationContextContainer"
        eType="#//OrchestrationContextContainer" containment="true" resolveProxies="false"
        eOpposite="#//OrchestrationContextContainer/orchestration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocations" lowerBound="1"
        upperBound="-1" containment="true" resolveProxies="false" eOpposite="#//Invocation/orchestration">
      <eGenericType eClassifier="#//Invocation">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrchestrationContext" eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UselessOrchestrationContext"/>
    </eAnnotations>
    <eOperations name="getOrchestration" lowerBound="1" eType="#//Orchestration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orchestrationContextContainer"
        lowerBound="1" eType="#//OrchestrationContextContainer" resolveProxies="false"
        eOpposite="#//OrchestrationContextContainer/orchestrationContexts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocationContexts" upperBound="-1"
        eType="#//InvocationContext" resolveProxies="false" eOpposite="#//InvocationContext/orchestrationContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" containment="true"
        resolveProxies="false">
      <eGenericType eClassifier="#//Type">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrchestrationContextContainer" eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UselessOrchestrationContextContainer"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orchestration" lowerBound="1"
        eType="#//Orchestration" eOpposite="#//Orchestration/orchestrationContextContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orchestrationContexts"
        upperBound="-1" eType="#//OrchestrationContext" containment="true" eOpposite="#//OrchestrationContext/orchestrationContextContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//ModelElement">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    </eTypeParameters>
    <eOperations name="getType" lowerBound="1">
      <eGenericType eClassifier="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaClass">
        <eTypeArguments eTypeParameter="#//Type/T"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getValue" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Invocation" abstract="true" eSuperTypes="#//ModelElement">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Activity"/>
    </eTypeParameters>
    <eOperations name="getFactoryComponent" lowerBound="1" eType="#//FactoryComponent"/>
    <eOperations name="getInvocationActivityContracts" upperBound="-1" eType="#//ActivityContract"/>
    <eOperations name="getInvocationActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getInvocationActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eOperations name="getInvocationActivityContracts" upperBound="-1" eType="#//ActivityContract">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eOperations name="getInvocationContexts" upperBound="-1" eType="#//InvocationContext"/>
    <eOperations name="getInvocationContexts" upperBound="-1" eType="#//InvocationContext">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getInvocationContexts" upperBound="-1" eType="#//InvocationContext">
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eOperations name="getInvocationContexts" upperBound="-1" eType="#//InvocationContext">
      <eParameters name="type">
        <eGenericType eClassifier="#//Type">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
      <eParameters name="mode" eType="#//ContractMode"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orchestration" lowerBound="1"
        eType="#//Orchestration" resolveProxies="false" eOpposite="#//Orchestration/invocations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocationContextContainer"
        eType="#//InvocationContextContainer" containment="true" resolveProxies="false"
        eOpposite="#//InvocationContextContainer/invocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1">
      <eGenericType eTypeParameter="#//Invocation/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvocationContext" eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="MandatoryName UniqueName ValidActivityContract ValidActivityContractType ValidContext ValidExposedContract ValidExposedContractType MandatoryTypeValue UselessType"/>
    </eAnnotations>
    <eOperations name="getFactoryComponent" lowerBound="1" eType="#//FactoryComponent"/>
    <eOperations name="getInvocation" lowerBound="1">
      <eGenericType eClassifier="#//Invocation">
        <eTypeArguments/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocationContextContainer"
        lowerBound="1" eType="#//InvocationContextContainer" resolveProxies="false"
        eOpposite="#//InvocationContextContainer/invocationContexts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="factoryComponentExposedContract"
        eType="#//FactoryComponentContract" resolveProxies="false" eOpposite="#//FactoryComponentContract/invocationContexts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orchestrationContext" eType="#//OrchestrationContext"
        resolveProxies="false" eOpposite="#//OrchestrationContext/invocationContexts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityContract" lowerBound="1"
        eType="#//ActivityContract"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" containment="true"
        resolveProxies="false">
      <eGenericType eClassifier="#//Type">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//ContractMode"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvocationContextConnector" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocationContextContainer"
        lowerBound="1" eType="#//InvocationContextContainer" resolveProxies="false"
        eOpposite="#//InvocationContextContainer/invocationContextConnectors"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceInvocationContext"
        lowerBound="1" eType="#//InvocationContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetInvocationContext"
        lowerBound="1" eType="#//InvocationContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvocationContextContainer" eSuperTypes="#//ModelElement">
    <eOperations name="getFactoryComponent" lowerBound="1" eType="#//FactoryComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocation" lowerBound="1"
        resolveProxies="false" eOpposite="#//Invocation/invocationContextContainer">
      <eGenericType eClassifier="#//Invocation">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocationContexts" upperBound="-1"
        eType="#//InvocationContext" containment="true" resolveProxies="false" eOpposite="#//InvocationContext/invocationContextContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocationContextConnectors"
        upperBound="-1" eType="#//InvocationContextConnector" containment="true" resolveProxies="false"
        eOpposite="#//InvocationContextConnector/invocationContextContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContractMode">
    <eLiterals name="In" literal="In"/>
    <eLiterals name="Out" value="1" literal="Out"/>
    <eLiterals name="In_Out" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="org.eclipse.emf.common.util.URI"/>
</ecore:EPackage>
