<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fcore"
    nsURI="http://www.eclipse.org/egf/1.0.0/fcore" nsPrefix="fcore">
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true">
    <eOperations name="getExternalName" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iD" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" abstract="true" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contractContainer" eType="#//ContractContainer"
        containment="true" resolveProxies="false" eOpposite="#//ContractContainer/activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FactoryComponent" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewpointContainer" eType="#//ViewpointContainer"
        containment="true" resolveProxies="false" eOpposite="#//ViewpointContainer/factoryComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orchestration" eType="#//Orchestration"
        containment="true" resolveProxies="false" eOpposite="#//Orchestration/factoryComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewpointContainer" eSuperTypes="#//ModelElement">
    <eOperations name="getViewpoint" eType="#//Viewpoint">
      <eParameters name="clazz">
        <eGenericType eClassifier="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaClass">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="factoryComponent" lowerBound="1"
        eType="#//FactoryComponent" resolveProxies="false" eOpposite="#//FactoryComponent/viewpointContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewpoints" upperBound="-1"
        eType="#//Viewpoint" containment="true" resolveProxies="false" eOpposite="#//Viewpoint/viewerpointContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Viewpoint" abstract="true" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="viewerpointContainer" lowerBound="1"
        eType="#//ViewpointContainer" resolveProxies="false" eOpposite="#//ViewpointContainer/viewpoints"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Orchestration" abstract="true" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="factoryComponent" lowerBound="1"
        eType="#//FactoryComponent" resolveProxies="false" eOpposite="#//FactoryComponent/orchestration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocations" upperBound="-1"
        containment="true" resolveProxies="false" eOpposite="#//Invocation/orchestration">
      <eGenericType eClassifier="#//Invocation">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orchestrationContextContainer"
        eType="#//OrchestrationContextContainer" containment="true" resolveProxies="false"
        eOpposite="#//OrchestrationContextContainer/orchestration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrchestrationContextContainer" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="orchestration" lowerBound="1"
        eType="#//Orchestration" eOpposite="#//Orchestration/orchestrationContextContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrchestrationContext" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contract" lowerBound="1"
        eType="#//Contract" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contexts" upperBound="-1"
        eType="#//Context" resolveProxies="false" eOpposite="#//Context/orchestrationContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" containment="true"
        resolveProxies="false">
      <eGenericType eClassifier="#//Type">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Invocation" abstract="true" eSuperTypes="#//ModelElement">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Activity"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orchestration" lowerBound="1"
        eType="#//Orchestration" resolveProxies="false" eOpposite="#//Orchestration/invocations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextContainer" eType="#//ContextContainer"
        containment="true" resolveProxies="false" eOpposite="#//ContextContainer/invocation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1">
      <eGenericType eTypeParameter="#//Invocation/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//ModelElement">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    </eTypeParameters>
    <eOperations name="getType" lowerBound="1">
      <eGenericType eClassifier="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaClass">
        <eTypeArguments eTypeParameter="#//Type/T"/>
      </eGenericType>
    </eOperations>
    <eOperations name="getValue" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeObject" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//Type">
      <eTypeArguments eTypeParameter="#//TypeObject/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeClass" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eGenericSuperTypes eClassifier="#//Type">
      <eTypeArguments eTypeParameter="#//TypeClass/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContractContainer" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
        eType="#//Activity" resolveProxies="false" eOpposite="#//Activity/contractContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contracts" upperBound="-1"
        eType="#//Contract" containment="true" resolveProxies="false" eOpposite="#//Contract/contractContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contract" eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UniqueContractName"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contractContainer" lowerBound="1"
        eType="#//ContractContainer" resolveProxies="false" eOpposite="#//ContractContainer/contracts"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatory" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//ContractMode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" containment="true"
        resolveProxies="false">
      <eGenericType eClassifier="#//Type">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContractConnector" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextContainer" eType="#//ContextContainer"
        resolveProxies="false" eOpposite="#//ContextContainer/connectors"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Contract"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Contract"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextContainer" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocation" resolveProxies="false"
        eOpposite="#//Invocation/contextContainer">
      <eGenericType eClassifier="#//Invocation">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contexts" upperBound="-1"
        eType="#//Context" containment="true" resolveProxies="false" eOpposite="#//Context/contextContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" upperBound="-1"
        eType="#//ContractConnector" containment="true" resolveProxies="false" eOpposite="#//ContractConnector/contextContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Context" eSuperTypes="#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="UniqueContextName ValidContract"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextContainer" lowerBound="1"
        eType="#//ContextContainer" resolveProxies="false" eOpposite="#//ContextContainer/contexts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invocationContract" lowerBound="1"
        eType="#//Contract"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orchestrationContext" eType="#//OrchestrationContext"
        eOpposite="#//OrchestrationContext/contexts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" containment="true"
        resolveProxies="false">
      <eGenericType eClassifier="#//Type">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContractMode">
    <eLiterals name="In" literal="In"/>
    <eLiterals name="Out" value="1" literal="Out"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="org.eclipse.emf.common.util.URI"/>
</ecore:EPackage>
