<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mapping"
    nsURI="http://www.eclipse.org/egf/1.0.0/mapping" nsPrefix="mapping">
  <eClassifiers xsi:type="ecore:EClass" name="MappingViewpoint" eSuperTypes="FactoryComponent.ecore#//Viewpoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="#//MappingDomain" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping" abstract="true" eSuperTypes="FactoryComponent.ecore#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="MappingDomain" eSuperTypes="#//Mapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass Domain.ecore#//Domain" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass Domain.ecore#//Domain" resolveProxies="false"/>
  </eClassifiers>
</ecore:EPackage>
