<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pattern"
    nsURI="http://www.eclipse.org/egf/1.0.0/pattern" nsPrefix="pattern">
  <eClassifiers xsi:type="ecore:EClass" name="Pattern" eSuperTypes="#//PatternElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="headerMethod footerMethod"/>
    </eAnnotations>
    <eOperations name="getMethod" eType="#//PatternMethod">
      <eParameters name="name" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="headerMethod" lowerBound="1"
        eType="#//PatternMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//PatternMethod" containment="true" resolveProxies="false" eOpposite="#//PatternMethod/pattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="footerMethod" lowerBound="1"
        eType="#//PatternMethod"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superPattern" eType="#//Pattern"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orchestration" upperBound="-1"
        eType="#//Call" containment="true" eOpposite="#//Call/pattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//PatternParameter" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nature" lowerBound="1"
        eType="#//PatternNature" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//PatternVariable" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initMethod" lowerBound="1"
        eType="#//PatternMethod"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternMethod" eSuperTypes="Fcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
        eType="#//Pattern" resolveProxies="false" eOpposite="#//Pattern/methods"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patternFilePath" lowerBound="1"
        eType="ecore:EDataType Fcore.ecore#//URI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternParameter" eSuperTypes="Fcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="query" eType="#//Query"
        containment="true" resolveProxies="false" eOpposite="#//Query/parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternEngine" abstract="true" eSuperTypes="Fcore.ecore#//ModelElement">
    <eOperations name="execute" eExceptions="#//PatternException">
      <eParameters name="context" lowerBound="1" eType="#//PatternContext"/>
    </eOperations>
    <eOperations name="translate" eExceptions="#//PatternException"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
        eType="#//Pattern" changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternLibrary" eSuperTypes="#//PatternElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//PatternElement" containment="true" resolveProxies="false" eOpposite="#//PatternElement/container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" upperBound="-1"
        eType="#//String2PatternList" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternElement" abstract="true" eSuperTypes="Fcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//PatternLibrary"
        resolveProxies="false" eOpposite="#//PatternLibrary/elements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternViewpoint" eSuperTypes="Fcore.ecore#//Viewpoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="libraries" upperBound="-1"
        eType="#//PatternLibrary" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternNature" abstract="true" eSuperTypes="Fcore.ecore#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PatternContext" instanceClassName="org.eclipse.egf.model.PatternContext"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PatternException" instanceClassName="org.eclipse.egf.model.PatternException"/>
  <eClassifiers xsi:type="ecore:EClass" name="PatternCall" eSuperTypes="#//AbstractPatternCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterMatching" upperBound="-1"
        eType="#//Paramerter2ParameterMap" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Paramerter2ParameterMap" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//PatternParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="#//PatternParameter"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Call" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
        eType="#//Pattern" eOpposite="#//Pattern/orchestration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MethodCall" eSuperTypes="#//Call">
    <eStructuralFeatures xsi:type="ecore:EReference" name="called" lowerBound="1"
        eType="#//PatternMethod"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternVariable" eSuperTypes="Fcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractPatternCall" abstract="true"
      eSuperTypes="#//Call">
    <eStructuralFeatures xsi:type="ecore:EReference" name="called" lowerBound="1"
        eType="#//Pattern"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternInjectedCall" eSuperTypes="#//AbstractPatternCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
        eType="#//PatternVariable" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Query" abstract="true">
    <eOperations name="getQueryContext">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        eType="#//PatternParameter" resolveProxies="false" eOpposite="#//PatternParameter/query"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extensionId" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicQuery" eSuperTypes="#//Query"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringQuery" eSuperTypes="#//Query"/>
  <eClassifiers xsi:type="ecore:EClass" name="CustomQuery" eSuperTypes="#//Query"/>
  <eClassifiers xsi:type="ecore:EClass" name="String2PatternList" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//PatternElement"/>
  </eClassifiers>
</ecore:EPackage>
