<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecoreToolsExtension"
    nsURI="http://www.eclipse.org/egf/1.0.0/generationChainEcoreToolsExtension" nsPrefix="ecoreToolsExtension">
  <eAnnotations source="http://www.thalesgroup.com/mde/2010/extension">
    <details key="extensibleProviderFactory" value="true"/>
    <details key="childCreationExtenders" value="true"/>
    <details key="useUUIDs" value="true"/>
    <details key="useIDAttributes" value="false"/>
  </eAnnotations>
  <eAnnotations source="http://www.thalesgroup.com/mde/mdsofa/dsl/2007/dslfactory">
    <details key="extensibleProviderFactory" value="true"/>
    <details key="childCreationExtenders" value="true"/>
    <details key="useUUIDs" value="true"/>
    <details key="useIDAttributes" value="false"/>
  </eAnnotations>
  <eAnnotations source="http://www.thalesgroup.com/mde/ecore/documentation">
    <details key="description"/>
    <details key="usage guideline"/>
    <details key="used in levels"/>
    <details key="usage examples"/>
    <details key="constraints"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="EcoreToolsGeneration" eSuperTypes="platform:/plugin/org.eclipse.egf.portfolio.genchain/model/generationChain.ecore#//EcoreElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
