<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="builddeploy" nsURI="http://www.eclipse.org/egf/1.0.0/builddeploy"
    nsPrefix="builddeploy">
  <eClassifiers xsi:type="ecore:EClass" name="HudsonDeployment" eSuperTypes="platform:/plugin/org.eclipse.egf.portfolio.eclipse.build/model/BuildCore.ecore#//Deployment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assignedNode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jdkName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="antName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buildId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="yyyyMMdd-HHmm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userDeployServerUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userDeployJobName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//User" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" upperBound="-1"
        eType="#//Trigger" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generationLocation" eType="#//GenerationLocation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="login" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="permission" lowerBound="1"
        eType="#//PermissionType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PermissionType">
    <eLiterals name="READ" value="1"/>
    <eLiterals name="EXECUTE" value="2"/>
    <eLiterals name="WRITE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CronTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="planning" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="00 06 * * *"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SCMTrigger" eSuperTypes="#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="planning" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="00 * * * *"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenerationLocation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="folderName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
  </eClassifiers>
</ecore:EPackage>
