<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="buildstep" nsURI="http://www.eclipse.org/egf/1.0.2/buildstep"
    nsPrefix="buildstep">
  <eClassifiers xsi:type="ecore:EClass" name="ResultStep" abstract="true" eSuperTypes="BuildCore.ecore#//Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="CleanStep" eSuperTypes="BuildCore.ecore#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//CLEAN_TYPE"
        defaultValueLiteral="Workspace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuildStep" eSuperTypes="BuildCore.ecore#//Step #//AbstractBuildLocationContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true" eOpposite="#//Component/buildStep"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allPlatforms" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noBuildersInvocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="skipComponentsRegex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=".*\.source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PublishStep" eSuperTypes="#//ResultStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generateSources" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generateDropins" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestStep" eSuperTypes="BuildCore.ecore#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="launchConfigurationPath"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeCoverage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AntStep" eSuperTypes="BuildCore.ecore#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xml" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runInEclipse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavadocStep" eSuperTypes="BuildCore.ecore#//Step">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sources" lowerBound="1"
        upperBound="-1" eType="#//SourceBuildLocation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="includes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="excludes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="links" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EGFSystemProperty" eSuperTypes="BuildCore.ecore#//KeyValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="EgfStep" eSuperTypes="BuildCore.ecore#//Step">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//EGFSystemProperty" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="egfActivities" lowerBound="1"
        upperBound="-1" eType="#//EgfActivity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EgfActivity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregateStep" eSuperTypes="#//ResultStep">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publishSteps" upperBound="-1"
        eType="#//PublishStep"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="updateSiteUrls" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstallStep" eSuperTypes="BuildCore.ecore#//Step">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profile" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultSteps" upperBound="-1"
        eType="#//ResultStep"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="updateSiteUrls" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="featureNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="productNames" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="installResultStepsSourceFeatures"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="p2_os" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="p2_ws" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="p2_arch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CLEAN_TYPE">
    <eLiterals name="RESULT" literal="Result"/>
    <eLiterals name="WORKSPACE" value="1" literal="Workspace"/>
    <eLiterals name="NOTHING" value="2" literal="Nothing"/>
    <eLiterals name="TOOLS" value="3" literal="Tools"/>
    <eLiterals name="ALL" value="4" literal="All"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractBuildLocation" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PatternBuildLocation" abstract="true"
      eSuperTypes="#//AbstractBuildLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractBuildLocationContainer" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="buildLocations" upperBound="-1"
        eType="#//AbstractBuildLocation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuildLocationContainer" eSuperTypes="#//AbstractBuildLocationContainer #//AbstractBuildLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceBuildLocation" abstract="true"
      eSuperTypes="#//PatternBuildLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suffix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryBuildLocation" abstract="true"
      eSuperTypes="#//PatternBuildLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suffix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalBuildLocation" eSuperTypes="#//SourceBuildLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetPlatformBuildLocation" eSuperTypes="#//BinaryBuildLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateSiteBuildLocation" eSuperTypes="#//BinaryBuildLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResultStepBuildLocation" eSuperTypes="#//BinaryBuildLocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultStep" lowerBound="1"
        eType="#//ResultStep"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstallStepBuildLocation" eSuperTypes="#//BinaryBuildLocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="installStep" lowerBound="1"
        eType="#//InstallStep"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RunningPlatformBuildLocation" eSuperTypes="#//BinaryBuildLocation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buildStep" lowerBound="1"
        eType="#//BuildStep" eOpposite="#//BuildStep/components"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plugin" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//Component"/>
</ecore:EPackage>
