<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="buildcore"
    nsURI="http://www.eclipse.org/egf/1.0.1/buildcore" nsPrefix="buildcore">
  <eClassifiers xsi:type="ecore:EClass" name="Item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemProperties" abstract="true" eSuperTypes="#//Item">
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyPackages" upperBound="-1"
        eType="#//PropertyPackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KeyValue" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//KeyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//PropertyType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyPackage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PropertyType">
    <eLiterals name="RUNTIME" literal="RUNTIME"/>
    <eLiterals name="INLINED" value="1" literal="INLINED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chain" eSuperTypes="#//ItemProperties">
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobs" lowerBound="1" upperBound="-1"
        eType="#//Job" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractStepContainer" abstract="true"
      eSuperTypes="#//ItemProperties">
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
        eType="#//Step" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Step" abstract="true" eSuperTypes="#//Item"/>
  <eClassifiers xsi:type="ecore:EClass" name="Job" eSuperTypes="#//AbstractStepContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scms" eType="#//SCM" containment="true"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployment" eType="#//Deployment"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StepContainer" eSuperTypes="#//AbstractStepContainer #//Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="SCM" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Deployment" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReuseStep" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reusedStep" lowerBound="1"
        eType="#//Step"/>
  </eClassifiers>
</ecore:EPackage>
