<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="buildtrigger"
    nsURI="http://www.eclipse.org/egf/1.0.0/buildtrigger" nsPrefix="buildtrigger">
  <eClassifiers xsi:type="ecore:EClass" name="CronTrigger" eSuperTypes="platform:/plugin/org.eclipse.egf.portfolio.eclipse.build/model/BuildCore.ecore#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="planning" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="00 06 * * *"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SCMTrigger" eSuperTypes="platform:/plugin/org.eclipse.egf.portfolio.eclipse.build/model/BuildCore.ecore#//Trigger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="planning" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="00 * * * *"/>
  </eClassifiers>
</ecore:EPackage>
